### ISSUE TITLE
Bibliotecas Ubuntu 16.04

### ISSUE THREAD

**Issue by LSantos06** [LSantos06/DataScience#1]
Para gerar o documento a partir do R Markdown deve-se instalar as seguintes bibliotecas no RStudio:
```
install.packages(c("jsonlite", "listviewer", "readxl", "readr", "ggplot2", "tidyverse", "stringr"))
```
Para instalar o readtext corretamente deve-se primeiramente executar os seguintes comandos no terminal:
```
sudo apt-get install libapparmor-dev
sudo apt-get install libpoppler-cpp-dev
```
```
install.packages("readtext")
```
Para geração de PDF a partir do R Markdown, deve-se executar o seguinte comando para instalação do LaTeX:
```
sudo apt-get install texlive-latex-base
sudo apt-get install texlive-latex-extra
sudo apt-get install texlive-xetex
```

**Comment by carlosaragon** [comment]
obg

**Comment by M-Tonin** [comment]
🐗
