### ISSUE TITLE
Bibliotecas Windows 10

### ISSUE THREAD

**Issue by LSantos06** [LSantos06/DataScience#2]
Baixe e instale a versão mais recente do R para Windows:
[R 3.5.1](https://cran.r-project.org)

Execute o seguinte comando para instalar as bibliotecas que são utilizadas no projeto:
```
install.packages(c("rmarkdown", "listviewer", "readxl", "readr", "readtext", "ggplot2", "tidyverse", "stringr",“igraph”))
```
Para geração do PDF no Windows deve-se instalar o MiKTeX Completo:
[MiKTeX 2.9](https://miktex.org/download)
No MikTeX, mudar a opção para baixar pacotes on fly (em settings)

**Comment by M-Tonin** [comment]
obg
👍 🦌 🇱🇨 🇳🇦 ✂️

**Comment by M-Tonin** [comment]
Adicionando o que faltou :
install.packages("devtools") 
devtools::install_github("kbenoit/readtext")
